version: 2.1
            
jobs:
  linting-old:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [linting]
      - run:
            name: install dependencies
            command: |
              wget -O ./hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
              chmod +x ./hadolint
      - run:
          name: lint check 1
          command: |
            npm install --save-dev htmlhint
            npx htmlhint "**/*.html"
      - run:
          name: lint check 2
          command: |
            ./hadolint ./app/Dockerfile
      - save_cache:
          paths: [node_modules]
          key: linting

  build-image-old:
      docker:
        - image: circleci/golang:1.15
          auth:
            username: ikenna1o2
            password: $DOCKERHUB_PASSWORD  
      steps:
        - checkout
        - setup_remote_docker:
            version: 19.03.13
        - run:
            name: build and push docker image
            command: |
              cd app
              docker build --tag=preappimage .
              echo $DOCKERHUB_PASSWORD | docker login -u ikenna1o2 --password-stdin
              docker tag preappimage ikenna1o2/preappimage
              docker push ikenna1o2/preappimage

        
workflows:
  default:
    jobs:
      - linting-old
      - build-image-old:
          requires: [linting-old]
